### ISSUE TITLE
Chart activity on interactive config

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/squared#389]
Now that interactive config is released ([2.6](https://github.com/meltano/meltano/releases/tag/v2.6.0)) we'll need to get a view on its usage to see if a) it's being used and b) is helpful in getting users up and running quicker.

**Comment by pnadolny13** [comment]
Explore refactoring to expose cli arguments up to the fact table so in the future we can get things like this without making changes to models.

**Comment by pnadolny13** [comment]
This isnt available for exploration right now because cli_contexts are not being explicitly parsed yet and are still using [execution level values](https://github.com/meltano/squared/blob/107e2316e3bfe3f3d22aaf66c5f64339e8c338fb/data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_exec_flattened.sql#L67) that are incorrect since the schema has changed from `option_key` to `options` https://github.com/meltano/meltano/blob/2307e3a838ea0764f63a9fd091ba19f6492bbe70/src/meltano/core/tracking/iglu-client-embedded/schemas/com.meltano/cli_context/jsonschema/1-1-0#L25.

- Parse the cli_context events properly and expose them downstream better. 


@tayloramurphy  For now I have an hacky adhoc query that uses string parsing and shows solid usage so far. If thats helpful.:

```
with base as (
    SELECT
        EVENT_CREATED_DATE,
        count(distinct execution_mapping.execution_id) as all_execs,
        count(distinct case when contexts LIKE '%interactive":true%' then execution_mapping.execution_id end) as interactive_execs,
        count(distinct execution_mapping.project_id) as all_projects,
        count(distinct case when contexts LIKE '%interactive":true%' then execution_mapping.project_id end)  as interactive_projects
    FROM prep.snowplow.stg_snowplow__events
    LEFT JOIN prep.workspace.execution_mapping
        ON stg_snowplow__events.event_id = execution_mapping.event_id
    where EVENT_CREATED_DATE >'2022-09-10' 
    AND (contexts LIKE '%meltano_version":"2.6.0%' OR contexts LIKE '%meltano_version":"2.7.0%')
    AND contexts LIKE '%command":"set","parent_command_hint":"config%'
    group by 1
)
select
    *,
    (interactive_execs/all_execs*1.0)*100 AS int_exec_pct,
    (interactive_projects/all_projects*1.0)*100 AS int_project_pct
from base
order by EVENT_CREATED_DATE desc;
```

**Comment by tayloramurphy** [comment]
@pnadolny13 this is great - thank you!

**Comment by pnadolny13** [comment]
Closing this because https://github.com/meltano/squared/issues/530 is for implementing a model for tracking this more consistently.
